### ISSUE TITLE
[BUG]: Incorrect API version check for snaphshot.storage.k8s.io/v1beta1

### ISSUE THREAD

**Issue by eanjtab** [dell/karavi-resiliency#60]
**Describe the bug**
  CSI expects the version of snaphshot.storage.k8s.io should be v1 for K8 1.20 but in K8 1.20.4 is still maintaining the version as v1beta1.  This worked after modifying the condition in the snapclass yaml definition file.

**To Reproduce**
1. Install K8 1.20.4 and validate if the version of snaphshot.storage.k8s.io is v1beta1 with the below command: -
    BL01cECCDADM01:~ # kubectl api-versions |grep snap
    snapshot.storage.k8s.io/v1beta1
    BL01cECCDADM01:~ #
2. Initiate CSI deployment and watch for the error were it says expects v1.

**Expected behavior**
Ideally the installation script should first validate and identify the version of the resource (shapshot) and then use that in the definition file.

**System Information (please complete the following information):**
 - OS/Version: SLES 15SP1
 - Kubernetes Version: 1.20.4

**Comment by coulof** [comment]
Hi @eanjtab,
According to the Kubernetes docs since 1.20 the `VolumeSnapshotDataSource` is GA : https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

Therefore the install script checks that the API version v1.

That being said these CRD are installed either manually for Kubernetes vanilla (see: https://dell.github.io/storage-plugin-docs/docs/installation/helm/powerflex/#volume-snapshot-crds) or comes with your distribution (like Openshift).

So if you (or your distro) decided to use the beta version of the Snapshots with Kubernetes 1.20, you can either upgrade or modify the driver installer here: https://github.com/dell/csi-powerscale/blob/master/helm/csi-isilon/templates/volumesnapshotclass.yaml#L1 to remove lines 1,2,3,5 (not 4!). 

HTH

**Comment by tdawe** [comment]
The required fix for this issue is part of the Dell EMC CSI Driver for PowerFlex (https://github.com/dell/csi-powerflex) and will be fixed as part of the 1.5 release.

**Comment by eanjtab** [comment]
> The required fix for this issue is part of the Dell EMC CSI Driver for PowerFlex (https://github.com/dell/csi-powerflex) and will be fixed as part of the 1.5 release.

Thanks, That's is good to know,  what is the fix that will be applied ?

**Comment by tdawe** [comment]
The snap class checks will be simplified to make it less restrictive.
